name: UserService CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout userService
      - name: Checkout userService
        uses: actions/checkout@v4

      # 2️⃣ Subir ambiente de teste
      - name: Setup Ambiente
        env:
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_DATA: ${{ secrets.ADMIN_DATA }}
          USER_ROLES: ${{ secrets.USER_ROLES }}
        run: |
          docker compose --profile test up -d --build

      # 3️⃣ Parar e remover containers
      - name: Stop and remove containers
        if: always()
        run: |
          docker compose --profile test down -v

      # 4️⃣ Salvar relatório
      - name: Save report html to artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-newman
          path: reports/relatorio.html
          if-no-files-found: warn